apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterpriseapp
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: enteriseapps
  project: "default"
  syncPolicy:   
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  source:
    path: dev
    repoURL: https://github.com/blcporgs/enterpriseappdeployments

