apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: myproject-deploy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: "default"
  source:
    path: '/dev'
    repoURL: 'https://github.com/blcporgs/enterpriseappdeployments'
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
