apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: enterpriseapp-deploy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: enteriseapp
  project: "default"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: foo // namespace of managing Argo CD instance 
    syncOptions:
    - CreateNamespace=true
  source:
    path: './dev'
    repoURL: 'https://github.com/blcporgs/enterpriseappdeployments'
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
