apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6ImlkMyIsImFwcGxpY2F0aW9uX25hbWUiOiJmcm9udGVuZCIsImFwcGxpY2F0aW9uX3VyaXMiOlsiZnJvbnRlbmQtcGF0aWVudC1vcnl4Lm5ldCJdLCJhcHBsaWNhdGlvbl92ZXJzaW9uIjoiYXBwLXZlcjMiLCJjZl9hcGkiOiJjZi1hcGktdXJsIiwibGltaXRzIjp7ImRpc2siOjEwMjQsImZkcyI6MTYzODQsIm1lbSI6MTAyNH0sIm5hbWUiOiJmcm9udGVuZCIsIm9yZ2FuaXphdGlvbl9pZCI6Im9yZy1pZCIsIm9yZ2FuaXphdGlvbl9uYW1lIjoib3JnLW5hbWUiLCJwcm9jZXNzX2lkIjoiaWQzIiwicHJvY2Vzc190eXBlIjoid2ViIiwic3BhY2VfaWQiOiJzcGFjZS1pZCIsInNwYWNlX25hbWUiOiJkZXYiLCJ1cmlzIjpbImZyb250ZW5kLXBhdGllbnQtb3J5eC5uZXQiXSwidXNlcnMiOm51bGwsInZlcnNpb24iOiJhcHAtdmVyMyJ9
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: frontend-vcapasenv
type: Opaque
