apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6ImlkMiIsImFwcGxpY2F0aW9uX25hbWUiOiJnYXRld2F5IiwiYXBwbGljYXRpb25fdXJpcyI6WyJnYXRld2F5LXJlc3RsZXNzLWZvc3NhLXdzLm5ldCJdLCJhcHBsaWNhdGlvbl92ZXJzaW9uIjoiYXBwLXZlcjIiLCJjZl9hcGkiOiJjZi1hcGktdXJsIiwibGltaXRzIjp7ImRpc2siOjEwMjQsImZkcyI6MTYzODQsIm1lbSI6MTAyNH0sIm5hbWUiOiJnYXRld2F5Iiwib3JnYW5pemF0aW9uX2lkIjoib3JnLWlkIiwib3JnYW5pemF0aW9uX25hbWUiOiJvcmctbmFtZSIsInByb2Nlc3NfaWQiOiJpZDIiLCJwcm9jZXNzX3R5cGUiOiJ3ZWIiLCJzcGFjZV9pZCI6InNwYWNlLWlkIiwic3BhY2VfbmFtZSI6ImRldiIsInVyaXMiOlsiZ2F0ZXdheS1yZXN0bGVzcy1mb3NzYS13cy5uZXQiXSwidXNlcnMiOm51bGwsInZlcnNpb24iOiJhcHAtdmVyMiJ9
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: gateway-vcapasenv
type: Opaque
