apiVersion: v1
data:
  CLOUD_OBJECT_STORAGE_0H_APIKEY: ImtleSI=
  CLOUD_OBJECT_STORAGE_0H_ENDPOINTS: ImNsb3VkLW9iamVjdC1zdG9yYWdlLWVuZHBvaW50cyI=
  CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_DESCRIPTION: IkF1dG8tZ2VuZXJhdGVkIGZvciBiaW5kaW5nIg==
  CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_NAME: ImFwaWtleS1uYW1lIg==
  CLOUD_OBJECT_STORAGE_0H_IAM_ROLE_CRN: InNlcnZpY2VSb2xlOldyaXRlciI=
  CLOUD_OBJECT_STORAGE_0H_IAM_SERVICEID_CRN: InNlcnZpY2VpZDpTZXJ2aWNlSWQi
  CLOUD_OBJECT_STORAGE_0H_RESOURCE_INSTANCE_ID: InJlc291cmNlLWlkIg==
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6ImlkMSIsImFwcGxpY2F0aW9uX25hbWUiOiJvcmRlcnMiLCJhcHBsaWNhdGlvbl91cmlzIjpbIm9yZGVycy1wcm91ZC1iaWxieS1yZi5uZXQiXSwiYXBwbGljYXRpb25fdmVyc2lvbiI6ImFwcC12ZXIxIiwiY2ZfYXBpIjoiY2YtYXBpLXVybCIsImxpbWl0cyI6eyJkaXNrIjoxMDI0LCJmZHMiOjE2Mzg0LCJtZW0iOjEwMjR9LCJuYW1lIjoib3JkZXJzIiwib3JnYW5pemF0aW9uX2lkIjoib3JnLWlkIiwib3JnYW5pemF0aW9uX25hbWUiOiJvcmctbmFtZSIsInByb2Nlc3NfaWQiOiJpZDEiLCJwcm9jZXNzX3R5cGUiOiJ3ZWIiLCJzcGFjZV9pZCI6InNwYWNlLWlkIiwic3BhY2VfbmFtZSI6ImRldiIsInVyaXMiOlsib3JkZXJzLXByb3VkLWJpbGJ5LXJmLm5ldCJdLCJ1c2VycyI6bnVsbCwidmVyc2lvbiI6ImFwcC12ZXIxIn0=
  VCAP_SERVICES: eyJjbG91ZC1vYmplY3Qtc3RvcmFnZSI6W3siYmluZGluZ19ndWlkIjoiYmluZGluZy1pZCIsImJpbmRpbmdfbmFtZSI6bnVsbCwiY3JlZGVudGlhbHMiOnsiYXBpa2V5Ijoia2V5IiwiZW5kcG9pbnRzIjoiY2xvdWQtb2JqZWN0LXN0b3JhZ2UtZW5kcG9pbnRzIiwiaWFtX2FwaWtleV9kZXNjcmlwdGlvbiI6IkF1dG8tZ2VuZXJhdGVkIGZvciBiaW5kaW5nIiwiaWFtX2FwaWtleV9uYW1lIjoiYXBpa2V5LW5hbWUiLCJpYW1fcm9sZV9jcm4iOiJzZXJ2aWNlUm9sZTpXcml0ZXIiLCJpYW1fc2VydmljZWlkX2NybiI6InNlcnZpY2VpZDpTZXJ2aWNlSWQiLCJyZXNvdXJjZV9pbnN0YW5jZV9pZCI6InJlc291cmNlLWlkIn0sImluc3RhbmNlX2d1aWQiOiJpbnN0YW5jZS1pZCIsImluc3RhbmNlX25hbWUiOiJDbG91ZCBPYmplY3QgU3RvcmFnZS0waCIsImxhYmVsIjoiY2xvdWQtb2JqZWN0LXN0b3JhZ2UiLCJuYW1lIjoiQ2xvdWQgT2JqZWN0IFN0b3JhZ2UtMGgiLCJwbGFuIjoiTGl0ZSIsInByb3ZpZGVyIjpudWxsLCJzeXNsb2dfZHJhaW5fdXJsIjpudWxsLCJ0YWdzIjpbIkxpdGUiLCJzdG9yYWdlIl0sInZvbHVtZV9tb3VudHMiOltdfV19
kind: Secret
metadata:
  creationTimestamp: null
  name: orders-vcapasenv
type: Opaque
